services:

  # Odoo Staging
  odoo_staging:
    build:
      context: ./srcs/staging/odoo
      dockerfile: Dockerfile
      args:
        ODOO_VERSION: 18.0 # Usato dal .env relativo
    env_file:
      - ./srcs/staging/odoo/.env
    volumes:
      - odoo_staging_data:/usr/lib/python3/dist-packages/odoo/addons
    depends_on:
      db_staging:
        condition: service_healthy
    networks:
      - staging

  db_staging:
    image: postgres:14
    container_name: db_staging
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
      POSTGRES_DB: postgres
    volumes:
      - db_staging_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - staging

  nginx_staging:
    build: 
      context: ./srcs/staging/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Porta per reverse proxy senza SSL
      - "8443:443" # Porta per reverse proxy con SSL (se abilitato)
    depends_on:
      - odoo_staging
    networks:
      - staging


  # Odoo Production
  odoo_production:
    build:
      context: ./srcs/prod/odoo
      dockerfile: Dockerfile
      args:
        ODOO_VERSION: 18.0 # Usato dal .env relativo
    env_file:
      - ./srcs/prod/odoo/.env
    volumes:
      - odoo_prod_data:/usr/lib/python3/dist-packages/odoo/addons
    depends_on:
      db_production:
        condition: service_healthy
    networks:
      - prod

  db_production:
    image: postgres:14
    container_name: db_production
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
      POSTGRES_DB: postgres
    volumes:
      - db_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - prod

  nginx_production:
    build:
      context: ./srcs/prod/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80" # Porta per reverse proxy senza SSL
      - "443:443" # Porta per reverse proxy con SSL (se abilitato)
    depends_on:
      - odoo_production
    networks:
      - prod

networks:
  prod:
    driver: bridge
    name: prod_network # Nome specifico per facilitare la gestione
  staging:
    driver: bridge
    name: staging_network # Nome specifico per facilitare la gestione


volumes:
  odoo_prod_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/odoo/prod
  odoo_staging_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/odoo/staging
  db_prod_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db/prod
  db_staging_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db/staging
